### ISSUE TITLE
the difference between Microcode Explorer output and optblock_t::func callback dump

### ISSUE THREAD

**Issue by TakahiroHaruyama** [RolfRolles/HexRaysDeob#8]
I'm implementing control flow unflattening in more matured level, related to https://github.com/RolfRolles/HexRaysDeob/issues/7.

I like to debug the code by using Microcode Explorer graph but sometimes (especially in MMAT_GLBOPT1) the output generated by Microcode Explorer is different from optblock_t::func callback dump in the same maturity level (e.g.. dumpBefore-MMAT_GLBOPT1-0.txt), so I can't refer to the graph in debugging.

Do you know the reason?

**Comment by RolfRolles** [comment]
No, I don't know what you're talking about.

**Comment by RolfRolles** [comment]
As it happens, I can sort of answer this question, but only because I've been reverse engineering Hex-Rays. This question isn't really related to an issue with the code I released for this project. It's pretty much just a generic question about Hex-Rays internals. You'll probably get better answers from Hex-Rays support.

Basically, the microcode explorer works by calling `gen_microcode` to produce an `mbl_array_t` at the specified maturity level, and then it stops immediately once that maturity level is reached. However, in ordinary operation of the decompiler, once the `mbl_array_t` has reached `MMAT_GLBOPT1`, Hex-Rays continues to optimize and transform the `mbl_array_t` before it reaches the next maturity level, `MMAT_GLBOPT2`.

In particular, in Hex-Rays 7.1, after reaching `MMAT_GLBOPT1`, the decompiler resolves stack variable addresses, refines the input arguments sizes, triggers block combination, performs common subexpression elimination, preallocates local variables, and does some other stuff that I haven't reverse engineered yet. Only after all of this is done does the decompiler update the maturity level of the `mbl_array_t`.

So, the reason the microcode explorer shows different results than something you dumped in an optblock_t handler is that, by the time your optblock_t handler is called, the `mbl_array_t` is not in the same state as it was when it originally reached `MMAT_GLBOPT1` -- further transformations have taken place since reaching `MMAT_GLBOPT1`.
